### PR TITLE
🛠 add 'sentry-trace' to CORS allowed headers

### PR DESCRIPTION
**Pull request by jgnieuwhof**
## Motivation
We're using Sentry in the new DeWrangle app.

Unfortunately we've been encountering some CORS related errors:
- https://github.com/kids-first/dewrangle/pull/26/files#diff-882b2c04b01b2e8b2cdcf1817c30ea503a8005f1c0d54cfff37053b6801fea85R29-R33

## Approach
Sentry uses the `sentry-trace` header to correlate issues across the front and back end pieces of an application:
- https://develop.sentry.dev/sdk/performance/#header-sentry-trace

Since this is a non-standard header we need to configure the CORS middleware to allow it:
- https://pypi.org/project/django-cors-headers/

I've made this change for both local development, and production, since Sentry is expected to work in both.

### CODE REVIEW

**Review by shanewilson — COMMENTED** [review]
Looks good! but I'll let the python devs give feedback

**Review by dankolbman — CHANGES_REQUESTED** [review]
Looks good! Can you just make sure to run it through the black formatter first? (line length 80)

**Comment by jgnieuwhof** [comment]
@dankolbman - sure thing; formatted both files via the command `black -l 80 <filename>`.

**Review by dankolbman — CHANGES_REQUESTED** [review]
# 🌵

Looks good!

**Review by dankolbman — APPROVED** [review]

**Review by gsantia — APPROVED** [review]
🔮

**Pull request merged**
