### PR TITLE
♻️ Refactor settings

### LINKED ISSUE #504: Extract feature settings
Our feature flags (`FEAT_`) and general settings currently need to be repeated across all our settings files although they are similar in all environments. We should be able to generalize these within one `features.py` file to reduce these repetitions when adding or changing features.

### PR DESCRIPTION
**Pull request by dankolbman**
Moves common feature settings into their file 

Closes #504

### CODE REVIEW

**Review by znatty22 — COMMENTED** [review]
There is a lot of repetitive code in all 3 settings files so can we also have a base settings file with shared settings that could be imported into development.py, testing.py, and production.py?

**Comment by dankolbman** [comment]
I think this is the start to combining the settings files. I'm debating whether we want to consolidate to one and handle everything through the environment via django-environ, but I want to transition slowly to make sure things don't break across environments.

**Review by znatty22 — APPROVED** [review]
👍

**Comment by znatty22** [comment]
> I think this is the start to combining the settings files. I'm debating whether we want to consolidate to one and handle everything through the environment via django-environ, but I want to transition slowly to make sure things don't break across environments.

I still vote for separate settings files as long as we can do something to DRY them up

**Comment by dankolbman** [comment]
I still need to clean out EGO settings here now that it's removed.

**Pull request merged**
